"""
Address-split ablation data prep.

The colleague's original complaint was that ADDRESS underperforms; the
open question was whether decomposing it into STREET/ZIPCODE/CITY (as
pii_table.py's own SPLIT/merged label schemes support) helps.

The actual document-generation driver that produced train.jsonl (the
letter templates + the render() calls with label scheme FLAT9) isn't
present in what TamerBERT.zip contained -- only pii_table.py's Case/field
generator and patterns.py survived, not the template-rendering script
itself. So a from-scratch regeneration with `--label-scheme merged`
(which would emit STREET/ZIPCODE/CITY as separate labels natively) isn't
possible here.

Instead: every ADDRESS span in train_filtered/eval_indist/eval_heldout_
templates was verified (see conversation) to follow the EXACT regular
format "<street+nr[+modifier]>, <4-digit zipcode> <city>" with zero
exceptions across all 2449+356+859 unique address strings -- this is a
deterministic consequence of pii_table.py's own fmt_address()/render()
code, not a guess. So splitting post-hoc via this one regex is exactly
equivalent to having generated with the "merged" scheme in the first
place; it is not a lossy heuristic.

eval_real.jsonl and ood_docs.jsonl are NOT touched -- they weren't
generated by pii_table.py (real LLM-filled docs / hand-authored OOD docs)
and are not guaranteed to follow this exact format. The trial script
instead merges the split model's STREET/ZIPCODE/CITY predictions back
into ADDRESS before scoring against those two surfaces, for a fair
head-to-head against the single-ADDRESS baseline.
"""
import json
import re

ADDR_RE = re.compile(r"^(.*), (\d{4}) (.+)$")


def split_entities(text, entities):
    out = []
    for e in entities:
        if e["label"] != "ADDRESS":
            out.append(e)
            continue
        s, en = e["start"], e["end"]
        sub = text[s:en]
        m = ADDR_RE.match(sub)
        assert m, f"address regex failed on {sub!r} -- was validated to never happen"
        street, zipc, city = m.group(1), m.group(2), m.group(3)
        street_start = s + m.start(1)
        zip_start = s + m.start(2)
        city_start = s + m.start(3)
        out.append({"start": street_start, "end": street_start + len(street), "label": "STREET"})
        out.append({"start": zip_start, "end": zip_start + len(zipc), "label": "ZIPCODE"})
        out.append({"start": city_start, "end": city_start + len(city), "label": "CITY"})
    return sorted(out, key=lambda x: x["start"])


def process(in_path, out_path):
    n_docs = n_split = 0
    with open(in_path, encoding="utf-8") as fin, open(out_path, "w", encoding="utf-8") as fout:
        for line in fin:
            d = json.loads(line)
            new_spans = split_entities(d["text"], d["spans"])
            n_split += sum(1 for s in new_spans if s["label"] in ("STREET", "ZIPCODE", "CITY"))
            d["spans"] = new_spans
            fout.write(json.dumps(d, ensure_ascii=False) + "\n")
            n_docs += 1
    print(f"{in_path} -> {out_path}: {n_docs} docs, {n_split} address-component spans")


if __name__ == "__main__":
    for fn in ["train_filtered.jsonl", "eval_indist.jsonl", "eval_heldout_templates.jsonl"]:
        process(fn, fn.replace(".jsonl", "_addrsplit.jsonl"))
